version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: textlint
    versions:
    - 11.7.7
    - 11.8.1
  - dependency-name: textlint-rule-no-dropping-the-ra
    versions:
    - 2.0.0
