# https://hexo.io/docs/github-pages.html
name: Docker

on:
  push:
    branches:
      - source # default branch

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc -y

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/uetchy/uechi.io:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}